services:
  # 1. BROKER MQTT
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: iot-mosquitto
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - iot-net

  # 2. NODE-RED (Simulatore Sensori + Logica)
  node-red:
    image: nodered/node-red:latest
    container_name: iot-nodered
    restart: always
    ports:
      - "1880:1880"
    env_file:
      - .env
    environment:
      - TZ=Europe/Rome
      - INFLUX_URL=${INFLUX_URL}
      - INFLUX_TOKEN=${INFLUX_TOKEN}
      - INFLUX_ORG=${INFLUX_ORG}
      - INFLUX_BUCKET=${INFLUX_BUCKET}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - SECTOR_MAP=${SECTOR_MAP}
    volumes:
      - ./nodered/data:/data
    networks:
      - iot-net

  # 3. INFLUXDB (Database Serie Temporali)
  influxdb:
    image: influxdb:2.7
    container_name: iot-influxdb
    restart: always
    ports:
      - "8086:8086"
    env_file:
      - .env
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUX_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUX_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUX_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUX_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUX_TOKEN}
    volumes:
      - ./influxdb/data:/var/lib/influxdb2
      - ./influxdb/config:/etc/influxdb2
    networks:
      - iot-net

  # 4. TELEGRAF (Ponte MQTT -> InfluxDB)
  telegraf:
    image: telegraf:latest
    container_name: iot-telegraf
    restart: always
    user: root
    depends_on:
      - influxdb
      - mosquitto
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    environment:
      - INFLUX_TOKEN=${INFLUX_TOKEN}
    networks:
      - iot-net

   # Questo container parte, lancia lo script Python e si spegne.
  dashboard-gen:
    image: python:3.11-slim
    container_name: dashboard-generator
    working_dir: /app
    volumes:
      # Montiamo la cartella corrente (.) dentro /app
      # Così lo script vede templates/, sensors/ e può scrivere in dashboards/
      - .:/app
    # Esegue lo script
    # Non serve rete o porte, lavora solo sui file
    command: python generate_dashboard.py
        

  # 5. GRAFANA (Dashboard)
  grafana:
    image: grafana/grafana:latest
    container_name: iot-grafana
    restart: always
    depends_on:
      influxdb:
        condition: service_started
      # Grafana NON parte finché dashboard-gen non ha finito con successo 
      dashboard-gen:
        condition: service_completed_successfully
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/data:/var/lib/grafana
      # 1. Montiamo il file di configurazione YAML
      - ./grafana/provisioning:/etc/grafana/provisioning
      
      # 2. Montiamo la cartella con i JSON (Template + Generato). Mappa la cartella 'dashboards' (PC) dentro la cartella 'json_files' (Cont
      # Nota: La destinazione DEVE coincidere con il path scritto nello YAML sopra
      - ./dashboards:/etc/grafana/provisioning/dashboards/json_files
    networks:
      - iot-net

  sensor-simulator:
    build: ./sensors
    container_name: iot-sensor-simulator
    restart: always
    depends_on:
      - mosquitto
    networks:
      - iot-net
    volumes:
      - ./sensors/config:/app/config

  # 6. AI SERVICE (Predictive Maintenance)
  ai-service:
    build: ./ai_service
    container_name: iot-ai-service
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - iot-net

networks:
  iot-net:
    driver: bridge
