services:
  # 1. BROKER MQTT
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: iot-mosquitto
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - iot-net

  # 2. NODE-RED (Simulatore Sensori + Logica)
  node-red:
    image: nodered/node-red:latest
    container_name: iot-nodered
    restart: always
    ports:
      - "1880:1880"
    environment:
      - TZ=Europe/Rome
    volumes:
      - ./nodered/data:/data
    networks:
      - iot-net

  # 3. INFLUXDB (Database Serie Temporali)
  influxdb:
    image: influxdb:2.7
    container_name: iot-influxdb
    restart: always
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword123
      - DOCKER_INFLUXDB_INIT_ORG=univaq
      - DOCKER_INFLUXDB_INIT_BUCKET=iot_bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token
    volumes:
      - ./influxdb/data:/var/lib/influxdb2
      - ./influxdb/config:/etc/influxdb2
    networks:
      - iot-net

  # 4. TELEGRAF (Ponte MQTT -> InfluxDB)
  telegraf:
    image: telegraf:latest
    container_name: iot-telegraf
    restart: always
    depends_on:
      - influxdb
      - mosquitto
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    environment:
      - INFLUX_TOKEN=my-super-secret-auth-token
    networks:
      - iot-net

  # 5. GRAFANA (Dashboard)
  grafana:
    image: grafana/grafana:latest
    container_name: iot-grafana
    restart: always
    depends_on:
      - influxdb
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/data:/var/lib/grafana
    networks:
      - iot-net

  sensor-simulator:
    build: ./sensors
    container_name: iot-sensor-simulator
    restart: always
    depends_on:
      - mosquitto
    networks:
      - iot-net
    volumes:
      - ./sensors/config:/app/config

networks:
  iot-net:
    driver: bridge
